workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/**/*.apk
    publishing:
      email:
        recipients:
          - prashantgure0@gmail.com
        notify:
          success: true
          failure: true
